### ISSUE TITLE
email@example reported as valid when it is infact invalid.

### ISSUE THREAD

**Issue by cookseym** [fredeil/email-validator.dart#10]
**Describe the bug :bug:** 
`email@example` is reported as a valid email, when it is infact invalid.

**To Reproduce**
EmailValidator.validate("email@example", true, false);

**Expected behavior**
return value should be false

**Comment by fredeil** [comment]
Thank you @cookseym. I will check this out

**Comment by fredeil** [comment]
Hi again @cookseym. I see that you are setting the `allowTopLevelDomains = true` in your validation. If you set the second parameter to `false` you should see the expected result.

**Comment by Cjoshua2** [comment]
This is still valid(abc@example.com) even though the TLD is default to false. Or am I just doing something wrong?

**Comment by fredeil** [comment]
I will look into it @Cjoshua2

**Comment by fredeil** [comment]
@Cjoshua2 abc@example.com will always be valid (regardless of the optional parameters). However, if you set `allowTopLevelDomains = true` the email `abc@example` will be valid
