### ISSUE TITLE
Email addresses with hyphen not valid

### ISSUE THREAD

**Issue by ChristianPauly** [fredeil/email-validator.dart#12]
**Describe the bug :bug:** 
Email addresses with a hyphen in the domain are marked as not valid but they are.

**To Reproduce**
Test the email address: test.nutzer@drk-nwm.care

**Expected behavior**
Should be correct.

**Additional context**
Validator returns false.

**Comment by fredeil** [comment]
Sounds odd based on this test case @ChristianPauly https://github.com/fredeil/email-validator.dart/blob/master/test/email_validator_test.dart#L59

Are you using the latest version?

**Comment by ChristianPauly** [comment]
hey, I have checked again and now it seems to work. Maybe our customers have used an older version of our product. Sorry for this.
