### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by britannio** [fredeil/email-validator.dart#19]
https://dart.dev/null-safety/migration-guide

**Comment by fredeil** [comment]
@britannio https://github.com/fredeil/email-validator.dart/pull/16, if you would like you could complete this for me? I'm not currently working with Dart

**Comment by fredeil** [comment]
See latest release @britannio

**Comment by britannio** [comment]
@fredeil Perfect, thanks for the timely update!
