### ISSUE TITLE
Update package version

### ISSUE THREAD

**Issue by TatsuUkraine** [fredeil/email-validator.dart#20]
It's time to get rid of `nullsafety` suffix)

https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

**Comment by AntonyLeons** [comment]
yep the branch looks good, please push the changes to pub.dev

**Comment by maxzod** [comment]
#21 done

**Comment by fredeil** [comment]
It's now published @TatsuUkraine, @AntonyLeons. Thank you @maxzod.

**Comment by TatsuUkraine** [comment]
Thanks
