### ISSUE TITLE
Is there any TLD checking?

### ISSUE THREAD

**Issue by syleishere** [fredeil/email-validator.dart#23]
test@test.commmmmmmmm returns valid for whatever reason.

Isn't there a downloadable list from arin.net you can toss in an array?

**Comment by fredeil** [comment]
`test@test.commmmmmmmm ` is valid.

Anything between 2 and 63 character is allowed. See here for more information https://www.icann.org/en/system/files/files/ua-factsheet-a4-17dec15-en.pdf

**Comment by fredeil** [comment]
@komposten's library for TLD checking seems legit if you need verify the TLD https://github.com/Komposten/public_suffix

**Comment by syleishere** [comment]
Might be a good flag for this project. I did find an error in your code that crashed my app, need you to add
if(email == null) { return false; }

**Comment by fredeil** [comment]
Are you using null safety in your code? @syleishere
