### ISSUE TITLE
[Help wanted] Improve documentation pub.dev score

### ISSUE THREAD

**Issue by fredeil** [fredeil/email-validator.dart#36]
Should be a low hanging fruit for anyone interested in contributing to the repository 😄 

![image](https://user-images.githubusercontent.com/17533404/142855856-babcd49f-93c1-4e3e-895d-12babf424e24.png)

**Comment by fredeil** [comment]
I'm not sure if this issue is totally relevant.

See https://github.com/dart-lang/pub-dev/issues/5285 for clarifications eventually

**Comment by fredeil** [comment]
See https://github.com/dart-lang/pub-dev/issues/5285#issuecomment-975464728 on how to go on to solve this issue

**Comment by maxzod** [comment]
this should be close now 😄
![image](https://user-images.githubusercontent.com/47630729/145712816-9115e90b-8bab-4e07-9c2a-2a10691eb70b.png)

**Comment by fredeil** [comment]
Yeah, they seem to have made some changes on the pub-dev website @maxzod. I'll close it for now, thanks!
