### ISSUE TITLE
Valid Result for "a#x@x.com" email type. Should be invalid.

### ISSUE THREAD

**Issue by ashishXenonstack** [fredeil/email-validator.dart#38]
Input : a#x@x.com

Current Result : Valid Email Format

Expected Result : Invalid

**Comment by fredeil** [comment]
This for example is valid:

https://github.com/fredeil/email-validator.dart/blob/master/test/email_validator_test.dart#L32

And 1 letter domains has already been discussed multiple times

**Comment by ashishXenonstack** [comment]
Apollogies for not mentioning the actual point here.
So, the '#' should not get accepted as valid character in 'a#x@x.com'.
I have verified the same with gmail and microsoft new userEmail format check.
Could you please clarify a little on this, thanks.

**Comment by captain-maramo** [comment]
According to RFC 5322 page 13 the "#" Symbol is a valid special character in mail adresses.
As an atext character its just not allowed as a first or last character in the adress and it is not allowed to appear twice.

**Comment by fredeil** [comment]
What is your conclusion then @captain-maramo

**Comment by captain-maramo** [comment]
I think that since 'a#x@x.com' is a valid mail address even if most mail providers would not accept it, this mail address should be evaluated as valid in the test since it is according to rfc.

**Comment by fredeil** [comment]
Closing this issue for now. Thanks for the support :)
