### ISSUE TITLE
Pub.dev score improvements (110 / 130) 

### ISSUE THREAD

**Issue by fredeil** [fredeil/email-validator.dart#41]
See https://pub.dev/packages/email_validator/score. Would be nice to have 130/130.

If someone has time I would appreciate it! Nice way to contribute to the project or open source as a first timer 👍

**Comment by k5924** [comment]
@fredeil Could I be assigned this?

**Comment by fredeil** [comment]
Sure mate @k5924

**Comment by k5924** [comment]
@fredeil I ran pana as you requested and I believe that it returned a full score as shown in the screenshot in PR [#42](https://github.com/fredeil/email-validator.dart/pull/42)

**Comment by fredeil** [comment]
Solved in #42
