### ISSUE TITLE
Incompatible Type Error

### ISSUE THREAD

**Issue by GooGam** [fredeil/email-validator.dart#44]
**Description**
Hi developer team, we were using email_validator package with version 2.0.1, and it was fine with the codebase. However, recently found out that updating version 2.1.2-2.1.16 will break the code with the error messages shown below:

![error 1](https://user-images.githubusercontent.com/102502135/182299269-5bd167e1-812b-42f5-865c-9ceeced00241.png)

![error 2](https://user-images.githubusercontent.com/102502135/182299293-8bf0634f-1716-406a-ac13-60822fbf05ae.png)

**Environments**
OS: MacOs Monterey v12.3 x64
Language: Dart SDK version: 2.17.6 (stable)
email_validator version: 2.1.2 or later

**Comment by fredeil** [comment]
you have an enum that is defined in your code called "Type". Same as email_validator has. Do you know if there is a way to have a private/internal enum type in dart?

**Comment by fredeil** [comment]
I'll release a new version with a new enum name..

**Comment by fredeil** [comment]
Can you try to update to 2.1.17 @GooGam ?

**Comment by fredeil** [comment]
https://pub.dev/packages/email_validator/versions/2.1.7

**Comment by GooGam** [comment]
Sorry for the late response. Thanks! It is all good now with v2.1.17.

**Comment by fredeil** [comment]
Fixed in #45

**Comment by fredeil** [comment]
Thanks for using the library and reporting error @GooGam 😄
