### ISSUE TITLE
Invalid validation when TLD contains an emoji

### ISSUE THREAD

**Issue by rishavsingla** [fredeil/email-validator.dart#46]
Email validator not working if we add emoji after "." 

For Example : ******@gmail.❤️️ -> This is not a valid email but email validator validates it.

**Comment by fredeil** [comment]
You're right @rishavsingla. Will look into that

**Comment by saikumarkusangi** [comment]
Hey @fredeil can i fix tthe issue ?

**Comment by fredeil** [comment]
Sure go ahead @saikumarkusangi !

**Comment by waliseddiqi** [comment]
Hey @fredeil since there is no update regarding this current PR. Can I give a look at this issue and provide a fix later ? I am not really familiar with codebase but will try to fix.
Thanks

**Comment by fredeil** [comment]
Sure go ahead @waliseddiqi , would be much appreciated 👍
