### ISSUE TITLE
False returned on email address

### ISSUE THREAD

**Issue by CabTheProgrammer** [fredeil/email-validator.dart#47]
Hello, I have an email address of the format xsdffgbh###@gmail.com (letters followed by three numbers)  that is being rejected by the package. Can anyone assist me with this?

**Comment by HeySreelal** [comment]
Can you share the code snippet? Also, please share the package's version code that you're using in your project. I've tried it myself and seems to be working fine:
```dart
void validateEmail() {
  var email = "xsdffgbh123@gmail.com";
  final res = EmailValidator.validate(email);
  print("Email is valid: $res");
}

validateEmail(); // => Email is valid: true
```

**Comment by fredeil** [comment]
Seems like a non issue? Please make sure you're using the latest version
