### ISSUE TITLE
Invalid email input is returning valid

### ISSUE THREAD

**Issue by marijam26** [fredeil/email-validator.dart#56]
I'm using your dependency for validating email address in my flutter project and for values like 'example@gmail.c' or 'example-@gmail.com' validate function is returning 'true' like it's valid value and it should return false.

**Comment by fredeil** [comment]
I cannot see why `example-@gmail.com` shouldn't be valid. The discussion about 1 letter TLD has been up for discussion ,as it's allowed by the spec but not really used. I might fix that one. Thanks for reporting

**Comment by fredeil** [comment]
I've added fix for 1 letter TLD https://github.com/fredeil/email-validator.dart/commit/98972bc6d87ab2916aef7d509c9f33586e4cc188

**Comment by pankaj-nikam** [comment]
Hi @fredeil , just a point of view, what about someone@x.com should it validate since x.com is a proper domain?

**Comment by fredeil** [comment]
That still works @pankaj-nikam. TLD = .com / .net / .org etc.

**Comment by pankaj-nikam** [comment]
Got it. Thanks 👍
