### ISSUE TITLE
Incompatibility with firebase_ui_oauth_google

### ISSUE THREAD

**Issue by mirdones** [fredeil/email-validator.dart#57]
Because no versions of firebase_ui_oauth match >1.5.3 <2.0.0 and firebase_ui_oauth 1.5.3 depends on firebase_ui_auth ^1.15.0, firebase_ui_oauth ^1.5.3 requires firebase_ui_auth ^1.15.0.
And because no versions of firebase_ui_auth match >1.15.0 <2.0.0 and firebase_ui_auth 1.15.0 depends on email_validator ^2.1.17, firebase_ui_oauth ^1.5.3 requires email_validator ^2.1.17.
Because no versions of firebase_ui_oauth_google match >1.3.3 <2.0.0 and firebase_ui_oauth_google 1.3.3 depends on firebase_ui_oauth ^1.5.3, firebase_ui_oauth_google ^1.3.3 requires firebase_ui_oauth ^1.5.3.
Thus, firebase_ui_oauth_google ^1.3.3 requires email_validator ^2.1.17.

**Comment by fredeil** [comment]
I'm not sure how this is on me? Could you elaborate? @mirdones

**Comment by mirdones** [comment]
There is some dependency problem after I updated this package.
Should I report it elsewhere?

**Comment by fredeil** [comment]
You might have duplicated packages installed, so a library that you use depends on this package using version `2.1.7`, but somewhere in your project you are using something that is using this package on latest version `3.0.0`. That might be my only guess?

How does your pubspecyaml look like

**Comment by mirdones** [comment]
this is my pubspec.yaml

  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_ui_auth: ^1.12.0
  firebase_ui_oauth_google: ^1.3.3
  firebase_analytics: ^11.0.1
  file_picker: ^8.0.3
  firebase_storage: ^12.0.1
  firebase_crashlytics: ^4.0.1
  firebase_performance: ^0.10.0+1
  url_launcher: ^6.3.0
  brasil_fields: ^1.14.3
  email_validator: ^3.0.0
  us_states: ^1.2.0
  cloud_functions: ^5.0.1
  http: ^1.2.1

**Comment by fredeil** [comment]
Seems like you have a circular dependency. `email_validator` version `2.1.7` is used inside the `firebase_ui_auth` package, therefore you can't update the package yet
