### ISSUE TITLE
Not working for tests without domain

### ISSUE THREAD

**Issue by deisold** [fredeil/email-validator.dart#6]
**Describe the bug :bug:** 
If a pass in 'kkkk@' is returns with confirming to be a valid email which I don't believe.

**To Reproduce**

**Expected behavior**
If I use https://isemail.info for instance, it says: "The general result is: Address is invalid for any purpose. The specific diagnosis is: Address has no domain part."

**Additional context**

**Comment by fredeil** [comment]
Should not do that, see this test: https://github.com/fredeil/email-validator.dart/blob/master/test/email_validator_test.dart#L68
